### ISSUE TITLE
Week 10?

### ISSUE THREAD

**Issue by joannakl** [nyu-ossd-s18/ky765-weekly#1]
@PhrydRhys  I can see the reason why you created the "blank posts" going up to week 10 in your blog, but for someone reading the posts, it makes it pretty hard to read them.

**Comment by PhrydRhys** [comment]
Okay, I understand. Instead of deleting them and the remaking the files when the time comes, is there a way to "deactivate" my blank posts? I'm not familiar with jekyll, but I would removing the .md in the file name do the trick?

**Comment by joannakl** [comment]
You can read more about the posts using jekyll at https://jekyllrb.com/docs/posts/ 
The required files names have to be very specific. I am wondering if starting the file names with an underscore or something like that will stop them from being pulled into the summary page. 

You should also be able to move them into a different directory until they are needed.

**Comment by PhrydRhys** [comment]
I see the basis behind your idea in the "Creating Post Files" of the jekyll documentation.

While it takes several seconds to update, it looks like appending something to mess up the formatting of the name in my [/_posts repo directory](https://github.com/nyu-ossd-s18/ky765-weekly/tree/master/_posts) does indeed prevent those files from showing up in [my blog page](https://nyu-ossd-s18.github.io/ky765-weekly/).

Thank you for the assistance!
